FROM mcr.microsoft.com/dotnet/core/sdk:3.1
RUN dotnet tool install --global ScopeAgent.Runner --version 0.3.0-beta.2
WORKDIR /app

COPY . ./
RUN dotnet build
RUN chmod +x entrypoint-test.sh
ENTRYPOINT ["./entrypoint-test.sh"]
