version: "3.4"

services:
  
  sqlserver:
    image: mcmoe/mssqldocker
    ports:
      - 1433:1433
    volumes:
      - sqlserver-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rest@erver01
      - MSSQL_PID=Express
      - MSSQL_DB=Restaurants
      - MSSQL_USER=restUser
      - MSSQL_PASSWORD=restPassw0rd
    healthcheck:
      test: ["CMD", "echo", "-e", "'\x1dclose\x0d'", "|", "telnet", "localhost", "1433"]
      start_period: 10s
      timeout: 10s
      retries: 3
      interval: 20s

  csharp-demo-app:
    build: .
    ports:
      - 8080:80
    volumes:
      - ~/.scope:/root/.scope
    environment:
      - CI
      - SCOPE_DSN=https://413d66d9314b4a1e9d7ea8674ce5d88c@app.scope.dev/
      - CIRCLECI
      - CIRCLE_BUILD_NUM
      - CIRCLE_BUILD_URL
      - JENKINS_URL
      - BUILD_ID
      - BUILD_NUMBER
      - BUILD_URL
      - GIT_COMMIT=$GIT_COMMIT
    links:
      - sqlserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/images/restaurant/00000000-0000-0000-0000-000000000000"]
      start_period: 10s
      timeout: 10s
      retries: 3
      interval: 20s
      
volumes:
  sqlserver-data: