name: Scope Tests

on: push

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Execute docker-compose
      run: |
        docker-compose -f ./docker-compose-test.yml up --build --exit-code-from=csharp-demo-app-test csharp-demo-app-test
        docker-compose -f ./docker-compose-test.yml down
      env:
        SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
        SCOPE_CODE_PATH: True
        SCOPE_RUNNER_ENABLED: True
